server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/libraria?createDatabaseIfNotExist=true
    username: dev813
    password: td@813*sql

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
